### ISSUE TITLE
TableWrapper rows clipped to 1000

### ISSUE THREAD

**Issue by Rdornier** [GReD-Clermont/simple-omero-client#56]
Hello, 

I've a problem dealing with TableWrapper. When I get a table from OMERO, the size of data (number of rows) are clipped to 1000 even if the table has more than 1000 rows. Strange thing : the rowCount indicates the correct number of rows.

![image](https://user-images.githubusercontent.com/64911638/225347575-9b962e90-3f11-4d58-b129-922db311eca4.png)

Edit : I'm using 5.12.2 version of simple-omero-client

**Comment by ppouchin** [comment]
Right. This is because the TablesFacility from the Java Gateway [limits](https://javadoc.scijava.org/OMERO/omero/gateway/facility/TablesFacility.html#getTable-omero.gateway.SecurityContext-long-) the number of rows retrieved to [1000](https://github.com/ome/omero-gateway-java/blob/master/src/main/java/omero/gateway/facility/TablesFacility.java#L60) if no number is given.

I could retrieve the information and always load the whole table, but I think it would be wiser to follow what the OME team did and only provide one method to retrieve rows in a provided range and one method to get the basic info (with no data), or even just the number of rows. That would incite devs to check the size is "acceptable" before downloading a table.

**Comment by Rdornier** [comment]
Ok, Thanks.
I didn't know about such limit for tables as well.
But is it possible to load the entire table from TableWrapper or is it only possible to get it using `client.getGateway().getFacility(TableFacility.class).getTable()` ?

> provide one method to retrieve rows in a provided range and one method to get the basic info 

Yes, it could be great to have a method in TableWrapper like `createTable(first row, last Row)` or `createFullTable()` or `createTable(boolean fullTable)`

**Comment by Rdornier** [comment]
I still have an issue. I've written the code below
```java

List<TableWrapper> tables = repoWrapper.getTables(client).stream().filter(e -> e.getName().contains(tableName)).collect(Collectors.toList());
            if(!tables.isEmpty()) {
                TableWrapper table = tables.get(0);
                TableData tableData = client.getGateway().getFacility(TablesFacility.class).getTable(client.getCtx(), table.getFileId(), 0, table.getRowCount(),
                        IntStream.range(0, table.getColumnCount()).toArray());
                return new TableWrapper(tableData);
            }
```

but `getFileId()` returns -1 and therefore the TableData is null.

Could you initialize TableWrapper with the file Id when we invoke `repoWrapper.getTables()` ?
Thanks
